import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";
import { ThemeSwitcher } from "./components/ThemeSwitcher";
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark"
      style={{ colorScheme: "dark" }}
      //suppressHydrationWarning={true}
    >
      <body className={inter.className}>
        <Providers>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <footer>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
              tempora, quas assumenda ipsa eveniet dolor ducimus aperiam minima
              porro eius fuga, nemo iure ea? Ut nam velit obcaecati deserunt
              molestiae. Lorem, ipsum dolor sit amet consectetur adipisicing
              elit. Mollitia ut illo, sunt rerum ad voluptatibus totam quos
              repudiandae impedit excepturi pariatur quibusdam dolore, eveniet
              quidem corporis enim doloribus accusantium laborum.
            </p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
